[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chiku"
version = "2.0.0"
authors = [
    { name="Devharsh Trivedi", email="devharsh@live.in" },
]
description = "Python package for efficient probabilistic polynomial approximation of arbitrary functions."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Mathematics",
]

# Core dependencies required to run the package
dependencies = [
    "numdifftools==0.9.42",
    "mpmath==1.4.1",
    "numpy==1.26.4",
    "scipy==1.17.1",
    "scikit-learn==1.8.0",
    "tensorflow==2.21.0"
]

[project.optional-dependencies]
dev = [
    "pytest==9.0.3",
    "setuptools==82.0.1"
]

[project.urls]
"Homepage" = "https://github.com/devharsh/chiku/blob/main/README.md"
"Docs" = "https://github.com/devharsh/chiku/tree/main/tests"
"Bug Tracker" = "https://github.com/devharsh/chiku/issues"
"Repository" = "https://github.com/devharsh/chiku"
"Security Policy" = "https://github.com/devharsh/chiku/security/policy"
